# Background and foreground colors
background = #000107
foreground = #cadbe1

# Standard colors
palette = 0=#000107
palette = 1=#9e6977
palette = 2=#b07876
palette = 3=#bc857b
palette = 4=#687da8
palette = 5=#8f749e
palette = 6=#7192b9
palette = 7=#cadbe1

# Bright colors
palette = 8=#595c62
palette = 9=#c88a9c
palette = 10=#db9b98
palette = 11=#e7a89b
palette = 12=#8aa0d7
palette = 13=#b695cb
palette = 14=#93b6e9
palette = 15=#baeeff
