$color = rgba(0, 1, 7, 1)
$inner_color = rgba(0, 1, 7, 0.66)
$outer_color = rgba(143, 116, 158, 1)
$font_color = rgba(202, 219, 225, 1)
$placeholder_color = rgba(202, 219, 225, 0.7)
$check_color = rgba(113, 146, 185, 1)
