background            #000107
foreground            #cadbe1

# black
color0  #000107
color8  #595c62

# red
color1  #9e6977
color9  #c88a9c

# green
color2  #b07876
color10 #db9b98

# yellow
color3  #bc857b
color11 #e7a89b

# blue
color4  #687da8
color12 #8aa0d7

# magenta
color5  #8f749e
color13 #b695cb

#cyan
color6  #7192b9
color14 #93b6e9

#white
color7  #cadbe1
color15 #baeeff


